using System.Net.Http.Json;
using System.Text.Json;
using System.Text.Json.Serialization;
using Microsoft.Extensions.Options;
using TwitchBridge.Models;

namespace TwitchBridge.Services;

/// <summary>
/// Owns the moderator-scoped Helix access token used by HelixApiService for
/// the follow-bonus check (moderator:read:followers). User access tokens
/// from an authorization-code flow (e.g. twitchtokengenerator.com's output)
/// are short-lived but come with a refresh token; this refreshes lazily on
/// use -- via Twitch's OAuth token endpoint directly, not TwitchLib.Api's
/// own refresh helper, which has a known bug where the returned ExpiresIn is
/// always 0 (TwitchLib/TwitchLib.Api#45) -- and persists the rotated
/// access+refresh token pair to a local file so it never needs to be
/// regenerated by hand again.
///
/// Twitch:ModeratorAccessToken/ModeratorRefreshToken in config only ever
/// seed the *first* token pair; once a persisted file exists it's the sole
/// source of truth and config values are never consulted again.
/// </summary>
public sealed class ModeratorTokenStore
{
    private const string TokenEndpoint = "https://id.twitch.tv/oauth2/token";
    private static readonly TimeSpan RefreshBuffer = TimeSpan.FromMinutes(5);

    private readonly ILogger<ModeratorTokenStore> _logger;
    private readonly TwitchOptions _options;
    private readonly HttpClient _http = new();
    private readonly SemaphoreSlim _lock = new(1, 1);
    private readonly string _statePath = Path.Combine("data", "moderator-token.json");
    private TwitchTokenState? _state;

    public ModeratorTokenStore(ILogger<ModeratorTokenStore> logger, IOptions<TwitchOptions> options)
    {
        _logger = logger;
        _options = options.Value;
    }

    /// <summary>
    /// Returns a currently-valid access token, transparently refreshing
    /// first if it's missing or expiring within RefreshBuffer. Null means
    /// the feature is unconfigured (no refresh token in config or on disk)
    /// or the refresh attempt itself failed -- callers should treat either
    /// as "skip the Helix call," not an error to propagate.
    /// </summary>
    public async Task<string?> GetAccessTokenAsync(CancellationToken ct = default)
    {
        await _lock.WaitAsync(ct);
        try
        {
            var state = await LoadOrSeedLockedAsync(ct);
            if (state is null || string.IsNullOrWhiteSpace(state.RefreshToken))
            {
                return null;
            }

            if (state.ExpiresAtUtc - RefreshBuffer > DateTimeOffset.UtcNow)
            {
                return state.AccessToken;
            }

            var refreshed = await RefreshLockedAsync(state, ct);
            return refreshed?.AccessToken;
        }
        finally
        {
            _lock.Release();
        }
    }

    private async Task<TwitchTokenState?> LoadOrSeedLockedAsync(CancellationToken ct)
    {
        if (_state is not null)
        {
            return _state;
        }

        if (File.Exists(_statePath))
        {
            try
            {
                await using var stream = File.OpenRead(_statePath);
                _state = await JsonSerializer.DeserializeAsync<TwitchTokenState>(stream, cancellationToken: ct);
                if (_state is not null)
                {
                    return _state;
                }
            }
            catch (JsonException ex)
            {
                _logger.LogWarning(ex, "Moderator token state at {Path} is corrupt; re-seeding from config", _statePath);
            }
        }

        if (string.IsNullOrWhiteSpace(_options.ModeratorRefreshToken))
        {
            return null;
        }

        // Seed from config with an already-expired timestamp -- forces an
        // immediate refresh below rather than trusting a possibly-stale
        // access token of unknown age the first time the app runs.
        _state = new TwitchTokenState
        {
            AccessToken = _options.ModeratorAccessToken,
            RefreshToken = _options.ModeratorRefreshToken,
            ExpiresAtUtc = DateTimeOffset.UnixEpoch,
        };
        return _state;
    }

    private async Task<TwitchTokenState?> RefreshLockedAsync(TwitchTokenState state, CancellationToken ct)
    {
        try
        {
            using var body = new FormUrlEncodedContent(new Dictionary<string, string>
            {
                ["grant_type"] = "refresh_token",
                ["refresh_token"] = state.RefreshToken,
                ["client_id"] = _options.ClientId,
                ["client_secret"] = _options.ClientSecret,
            });

            using var response = await _http.PostAsync(TokenEndpoint, body, ct);
            if (!response.IsSuccessStatusCode)
            {
                _logger.LogWarning("Moderator token refresh failed: HTTP {Status}", response.StatusCode);
                return null;
            }

            var payload = await response.Content.ReadFromJsonAsync<RefreshResponse>(cancellationToken: ct);
            if (payload is null || string.IsNullOrEmpty(payload.AccessToken))
            {
                _logger.LogWarning("Moderator token refresh returned an empty payload");
                return null;
            }

            _state = new TwitchTokenState
            {
                AccessToken = payload.AccessToken,
                // Twitch is supposed to always rotate the refresh token, but
                // fall back to the old one rather than lose the ability to
                // refresh again if a response ever omits it.
                RefreshToken = string.IsNullOrEmpty(payload.RefreshToken) ? state.RefreshToken : payload.RefreshToken,
                ExpiresAtUtc = DateTimeOffset.UtcNow.AddSeconds(payload.ExpiresIn > 0 ? payload.ExpiresIn : 3600),
            };
            await SaveLockedAsync(ct);
            _logger.LogInformation("Refreshed moderator Helix token, valid until {ExpiresAt}", _state.ExpiresAtUtc);
            return _state;
        }
        catch (Exception ex)
        {
            _logger.LogWarning(ex, "Moderator token refresh threw");
            return null;
        }
    }

    private async Task SaveLockedAsync(CancellationToken ct)
    {
        var directory = Path.GetDirectoryName(_statePath);
        if (!string.IsNullOrEmpty(directory))
        {
            Directory.CreateDirectory(directory);
        }

        var tmpPath = _statePath + ".tmp";
        await using (var stream = File.Create(tmpPath))
        {
            await JsonSerializer.SerializeAsync(stream, _state, new JsonSerializerOptions { WriteIndented = true }, ct);
        }
        File.Move(tmpPath, _statePath, overwrite: true);
    }

    private sealed class RefreshResponse
    {
        [JsonPropertyName("access_token")]
        public string AccessToken { get; set; } = "";

        [JsonPropertyName("refresh_token")]
        public string RefreshToken { get; set; } = "";

        [JsonPropertyName("expires_in")]
        public int ExpiresIn { get; set; }
    }
}
